### ISSUE TITLE
More enjoyable single map wads

### ISSUE THREAD

**Issue by axredneck** [obsidian-level-maker/Obsidian#122]
My suggestions:
- Single map wad should begin with weak monsters and end with tough ones (and a boss or a gotcha)
- Different parts of large map should look different (use different fabs)
- Powerful things (like a backpack or a chaingun) should not be placed at the beginning of such map (except secrets of cource)

**Comment by ghost** [comment]
To make sure I understand this right, you're almost describing a sort of very large map that has episode-like progression within the map itself? Sounds like a cool idea, especially with UDMF allowing for some higher limits. I'm not sure how much of that is doable at the moment, because I would have to learn more about how the various systems work that place monsters and weapons (right now, I think it just ensures that you should have enough weaponry to beat all of the monsters in a map).

I'll leave this open in case someone who understands those parts a little bit better has any input.

**Comment by ghost** [comment]
Not much activity, so I'll close this. That being said, we do recognize some of the weaknesses of single-map versus longer WADs, like the ones you've mentioned. We hope to improve this in time.

**Comment by axredneck** [comment]
But why did you close it if it's still an issue?
Also it's not "question" but "enhancement".

**Comment by ghost** [comment]
It's closed because there isn't a singular, tangible "issue" to address. Some of your suggestions may not be feasible with the current system and how it generates a map. I tried to respond to see if I understood your suggestions properly, and had no input for over two weeks on the subject.

**Comment by axredneck** [comment]
> I tried to respond to see if I understood your suggestions properly

My bad, i thought your question was rhetoric:
> ... you're almost describing a sort of very large map that has episode-like progression within the map itself? Sounds like a cool idea ...

 Yes, you understood my suggestions properly.

**Comment by ghost** [comment]
If that's the case, I will try to break this up into some more granular issues and create them individually so that they can be addressed.
