### ISSUE TITLE
Just 2 things about the hexen wads

### ISSUE THREAD

**Issue by revevil** [obsidian-level-maker/Obsidian#362]
Hello, I have been testing Hexen wads with Obsidian, and I do understand they are experimental, but still its really good! But 2 things I have noticed... There seems to be an issue with the height of the chandeliers. Sometimes they are lower than the ceiling. Also, there seems to be an issue with teleporters not working. These are the only things I've noticed so far. Obsidian is so awesome though! (I hope it is ok to post this kind of thing here. Please tell me if it is not.)

**Comment by ghost** [comment]
Feedback is welcome, be it here or Discord or the ZDoom forum where we have a thread as well.

Since the latest release, I have been able to fix teleporters and monster teleports/depots/traps, so the next release should have those in order. 

As far as the chandeliers, I've been wrangling that for a little bit. It used to be that they would ALWAYS be on the floor, but now it seems to be happening in areas where there is a sort of "overhang" in the room, or an area with a lower ceiling than the rest of the room. Hopefully I can get it squashed at some point.

**Comment by ghost** [comment]
I think the chandelier/ceiling thing issue for Hexen is finally fixed as of commit https://github.com/dashodanger/Obsidian/commit/f31e263182fbd1b2316d5c1ab77556902566f9e6. I'm going to close this, but feel free to bring up any other issues you encounter.

**Comment by revevil** [comment]
I'm not sure if I can comment with this issue being closed. I just wanted to say thank you! You are the best!
