### ISSUE TITLE
Chain link 'window' fencing is completely passable

### ISSUE THREAD

**Issue by FistsAkimbo** [obsidian-level-maker/Obsidian#364]
This is from the current unstable release from a few days ago.

Various forms of chain link window areas that have solid map geometry at the top of the fence, allow both monsters and players free movement past the fence, acting as though they were intended to be vines. This occurs with any window or railing setting in the map generator, but I have mine set to no movement for both. The fencing in question that I've seen affected (so far,) is the small and large chain link that runs diagonal squares/diamonds, and the other would be the thick, silver girder-esque ones that run cardinally.

[LOGS.txt](https://github.com/dashodanger/Obsidian/files/8181828/LOGS.txt)

On a side note, could the bug report wall texture be set to the debug mode so there's a way to turn it off?

**Comment by ghost** [comment]
I'll see if any of the prefab creators knows which fab you are referring to from your description. 

As far as the bug report wall texture, the high-vis error texture is already a toggle in the Debug module, unless you are referring to something else.

**Comment by GTD-Carthage** [comment]
Please provide a screenshot if you can so the fab can be identified.

**Comment by FistsAkimbo** [comment]
Sure: https://imgur.com/a/L0nytYa

As far as what I mean by the texture, it would be the '0 days since bug report without a log" wall texture.

**Comment by GTD-Carthage** [comment]
Unfortunately, I'm not sure why this is occurring. These are window fabs with simple midtex lines impassibility flag set. As an experiment though, I noticed you're playing with Hideous Destructor on. Can you try without the mod on?

If possible too, checking the map via a map editor such as Doom Builder to confirm if there is anything missing with regards to the line flags on these items because I am suspecting HD may be doing something unusual to them. (feel free to post the map WAD zipped up)

With regards to the message texture though - it is there for a reason. If this is too immersion-breaking though, you can disable by deleting the Lua file `gtd_pic_industrial_warning_pic.lua` inside `games/doom/fabs/picture`. You can turn this into a future-proof addon by simply emptying out the Lua file text and then zipping it up as an addon (zip up to the Lua text file with the correct directory structure and load it up as an addon).

**Comment by FistsAkimbo** [comment]
Frustratingly, it does seem to be HD exclusive, after I tested the maps with no mods in addition to a slew of other classics. But I don't see what could suddenly make the chains links and grates that Obsidian generates any different from old midtexture bridges and similar things that do not cause this to happen. Is there something unique to the way Obsidian is generating these that other maps don't have?

**Comment by ghost** [comment]
I think this might be a question better addressed to the HD devs themselves to see what their mod does that would cause such an incompatibility.

EDIT: To clarify, if there's a possible fix that retains compatibility in all other aspects, that is fine, but it may be something out of our hands.

**Comment by FistsAkimbo** [comment]
> I think this might be a question better addressed to the HD devs themselves to see what their mod does that would cause such an incompatibility.
> 
> EDIT: To clarify, if there's a possible fix that retains compatibility in all other aspects, that is fine, but it may be something out of our hands.

Appreciate your time and help, but it was a false alarm, my mistake. No other mod has subverted my expectations in so many ways over the years, I thought it had to have been something else. As far as I can tell, the Obsidian midtexture bars and fencing are completely normal, HD is just running a bizarre check. Should be in the clear to close this question.

**Comment by ghost** [comment]
Sounds good; let us know if anything else crops up
