### ISSUE TITLE
Show command line generator options?

### ISSUE THREAD

**Issue by coverslide** [obsidian-level-maker/Obsidian#481]
I like running Obsidian over the command line vs the gui. But it's hard to tell what the valid generator options would be without going through the lua files. I'd love if we had a separate terminal command just to show the generator options instead of just the command line options.

**Comment by ghost** [comment]
I'll have to do some brainstorming to see if this could easily be done in a way that won't overwhelm the user or terminal with information. I won't call command-line mode an "afterthought", but it was originally created as a batch mode more for use with premade CONFIG.txt files.

**Comment by ghost** [comment]
I'll keep this open because we're still finalizing the implementation, but builds on or after commit https://github.com/dashodanger/Obsidian/commit/05774be45791810372392abda42579341effd076 will have the ability to pass the -p or --printref parameter to the program. This will both display a reference of all keys and values to stdout, as well as print them to a file called REFERENCE.txt in your config/log directory for future reference. Here is an example of the output:

[REFERENCE.txt](https://github.com/dashodanger/Obsidian/files/9541463/REFERENCE.txt)

Let us know if this fits the bill for you.

**Comment by Phytolizer** [comment]
I've also added --printref-json in 2fe014b52e4b1bc0a3374580c7c8331df7b45240 for machine-readable output, and --update in c9bb104b1706e1b0ea5981e5b0177393c596abed to allow modifying the config file programmatically.

**Comment by coverslide** [comment]
@dashodanger @Phytolizer awesome, these look amazing!

Just for context I wanted to make a web-based frontend that calls obsidian in batch mode in the background, so the JSON format is especially helpful, thanks!

**Comment by ghost** [comment]
Yeah @Phytolizer crushed that. I'm still smoothing out some teething troubles, but things like the schema that he provided should be pretty accurate, with perhaps one or two additions.

**Comment by Phytolizer** [comment]
oh yeah, i forgot to mention the schema. it's here: https://github.com/dashodanger/Obsidian/blob/obsidian/tools/printref.schema.json

**Comment by coverslide** [comment]
Oh, one more thing, I know this isn't likely to change often, but is it possible to get the "Game Settings" params such as "game", "length", "engine", "theme" etc. in there?

**Comment by ghost** [comment]
I do need to add those as well....also, the existing references will need an additional level of nesting to account for the fact that some modules may have duplicate option names,

**Comment by ghost** [comment]
With Phyto's https://github.com/dashodanger/Obsidian/commit/1bd3b5c4f53d7f00e32a8d8dcded5f5dff5f60ff commit, that should close this one out. The printref routines and JSON schema have been updated to have options nested within modules, and the "Game Settings" options are accounted for as well.
