### ISSUE TITLE
PRBoom+ 2.6.2 Crashes On Any Obsidian Made Map

### ISSUE THREAD

**Issue by ForeskinJohn** [obsidian-level-maker/Obsidian#568]
ive tried boom compatibility, ive tried prboom compat, even vanilla and limit removing and every single time i get the error shown in the photo, what is the issue here? 
![Screenshot (51)](https://user-images.githubusercontent.com/64999311/219982303-12350201-3b01-4dd9-b576-1691ee7d5e5f.png)

**Comment by ForeskinJohn** [comment]
same goes for dsda doom

**Comment by ForeskinJohn** [comment]
Ultimate Doom 1.9

**Comment by dashodanger** [comment]
It's going to take a bit of re-writing the existing implementation, but basically Doom games other than Doom 2 have historically had trouble with missing materials/things due to the nature of their shared tables and fabs. I'll keep this open until a new stable release can be rolled out that hopefully fixes it.

**Comment by dashodanger** [comment]
I did a few more passes with the material checker and fixed some other tables and as of https://github.com/obsidian-level-maker/Obsidian/commit/911a2465b6634b812fd2d0ae097894563ff74986 when I generated a full game with PrBoom-Compat it is not reporting anything missing. These updates should be in the next stable release, or you can sync up manually if preferred.
