### ISSUE TITLE
The one Request , the one good movie :) - OBISIODIAN ON PK3 , THE MOD OF THE MODS .

### ISSUE THREAD

**Issue by Caiuzx** [obsidian-level-maker/Obsidian#593]
hi caligari78.
i am a doom fan since 94 - doom 1 - i eat it , i eat imp , i eat sign of evil .
Then thank you infinitely for your program, it is excellent. Oblige I already knew it , it was wonderful . let alone this :
My suggestions , in the manner of considering you the romero of generators :
1- can you consider choosing the rooms to implement in the generartor ? I make it with ultimate building and then import it and put it in the generator as the heck I want .  It creates community besides doom community 2. doomworld docet.
2 - CAN YOU MAKE A WAY , pardon the loud voice , TO TRANSFORM OBSIDIAN INTO A DOOM 2 MOD ? PK3 ? by doing this i load obsidian's mod INTO doom 2 and AS A ROUGULIKE I PLAY DIRECTLY WITHOUT DOING THE GENERATION FIRST AND THEN LOADING ,EVEN IF COMFORTABLE , BUT WITH DOOM ARSENAL mod AND CARRUCTION CARDS mod = BINDING OD ISACC steam game !!!!!!!
sorry for the outburst , no one has done it yet and I hope you do , someday , or me or whoever. 
3 - hello , with intinue as above :) you find me with Caiuz everywhere. :) :) 
4 - Vote god complex of ultraviolence at cocademons - (I am game designer ninja) for 30 old game doom 
5 - if you know those of gzdoom , can you tell them to implement save recognition , mods in the save ? thanks

**Comment by ghost** [comment]
Hello,
caligari78 was a member of the original ObAddon team and did initially host the Oblige repository for what would eventually become Obsidian, but he has since left the team. As far as your questions:
1 - You cannot import entire rooms as prefabs into the generator as it stands.
2 - Generating levels directly in the engine would be a request directed to source port developers.
3 - I don't understand this.
4 - I'm not sure what this is referring to.
5 - We do not have any say in the development of GZDoom.
