### ISSUE TITLE
Obsidian is not producing enough ammo and health items

### ISSUE THREAD

**Issue by KometFox** [obsidian-level-maker/Obsidian#676]
Obsidian version: v20 "Gate of Tartarus"
Specs:
OS: Xubuntu 22.04
CPU: AMD Ryzen 7 5700x 8 core
GPU: RTX 3060 Ti 

I have no idea why but for some reason Obsidian on my end produces scarce amount of health and ammo pickups despite I set the amount to "bit more" and every time I play those random generated maps there is never enough of ammo and health items to survive a encounter which limits me heavily with what mod pack I can play it the obsidian maps with. I also compiled the Obsidian program as instructed on the readme guide.

**Comment by ghost** [comment]
I've removed the attached log because it contained an unsanitized path.

That being said, we would need to look at an actual example WAD that shows the behavior that you are referring to. Barring the use of any unofficial addons, the monster placement and subsequent battle simulations should always produce enough weaponry and ammo to complete the level.

**Comment by KometFox** [comment]
[map_example.zip](https://github.com/user-attachments/files/17818017/map_example.zip)

Here is a example map, the initial starting area often starts up with some weapons and ammo but on other sections of the map there is almost no items as if the settings for ammo and health items were set to lower amount such as "less" or "scarce", maybe this example is still playable I haven't tested it. But I often use "Episodic" map generation which generates 12 levels or so and I had to rely on mods that adds alternative means to get supplies, as for obsidian itself I did not used any additional addons that may affect the item or monster placement. So all that I did was compiling Obsidian, tweaking the settings and then generating maps.

**Comment by ghost** [comment]
Hmm, not sure what to say, that map had 49 enemies and I ended with a shotgun, chaingun, plasma rifle, and BFG which is overkill already considering the highest tier enemy was a chaingunner. 

If you can find an example of a map being literally impossible to complete with the item distribution (including ammo/weapons dropped by defeated enemies which does factor into the counts) then we can reopen this, otherwise it's really too subjective to tackle.
